name: Build and Package for All Platforms

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact: MyApp.deb
          - os: windows-latest
            artifact: MyApp.exe
          - os: macos-latest
            artifact: MyApp.dmg

    steps:
    - uses: actions/checkout@v4

    # Install build dependencies
    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build g++ libglfw3-dev libgl1-mesa-dev libxkbcommon-dev libxinerama-dev

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install cmake ninja glfw

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install cmake ninja

    # Configure and build
    - name: Configure CMake
      run: cmake -B build -G Ninja

    - name: Build
      run: cmake --build build --config Release

    # Package
    - name: Package
      run: cd build && cpack

    # Upload artifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-package
        path: build/${{ matrix.artifact }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./release

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          release/**/*.exe
          release/**/*.dmg
          release/**/*.deb
